name: Uptime Monitor

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/50 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Check Website Uptime
      uses: lakuapik/gh-actions-http-status@v1
      with:
        sites: '["https://vyoma.world"]'
        expected: '[200]'
